[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Martin Weiss", email = "xweiss3@mendelu.cz"},
]
dependencies = [
    "pika>=1.3.2",
    "pymongo>=4.5.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

